/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import ArchUsuIntro.Music1;
import java.applet.AudioClip;
import javax.swing.JOptionPane;

/**
 *
 * @author GABRIEL-PC
 */
public class TiendaGV extends javax.swing.JFrame {

    String SelecMusica;
    private Object oMusica;

    /**
     * Creates new form TiendaGV
     */
    AudioClip sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Cancion/videoplayback (online-audio-converter.com).wav"));

    public TiendaGV() {
        initComponents();
        l.setText("");
        oMusica = null;

        txtArea.setVisible(false);
        txtBusqueda.setVisible(false);
        A.setVisible(false);
        btnReproducir.setVisible(false);
        btnDetener.setVisible(false);
        //Rock.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SelectMusic = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        A = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        l = new javax.swing.JLabel();
        btnReproducir = new javax.swing.JButton();
        btnDetener = new javax.swing.JButton();
        Pago = new javax.swing.JButton();
        DRT = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SelectMusic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Musica", "Peliculas" }));
        SelectMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectMusicActionPerformed(evt);
            }
        });
        getContentPane().add(SelectMusic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Opciones");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        A.setText("Buscar");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        getContentPane().add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 20));
        getContentPane().add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 350, 260));

        l.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        l.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 380, 30));

        btnReproducir.setText("Reproducir");
        btnReproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproducirActionPerformed(evt);
            }
        });
        getContentPane().add(btnReproducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 30));

        btnDetener.setText("Detener");
        btnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 90, 30));

        Pago.setText("Pagar");
        Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagoActionPerformed(evt);
            }
        });
        getContentPane().add(Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 90, 30));

        DRT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rancheras", "Rock", "Electronica", "Rut" }));
        DRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DRTActionPerformed(evt);
            }
        });
        getContentPane().add(DRT, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 60, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dbz.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 480));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectMusicActionPerformed
        SelecMusica = SelectMusic.getSelectedItem().toString();

        if (SelecMusica == "Musica") {
            txtArea.setVisible(true);
            txtBusqueda.setVisible(true);

            A.setVisible(true);

        } else if (SelecMusica == "Peliculas") {
            txtArea.setVisible(false);
            txtBusqueda.setVisible(false);
            A.setVisible(false);

        }
    }//GEN-LAST:event_SelectMusicActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        buscar();
        txtArea.setVisible(true);
    }//GEN-LAST:event_AActionPerformed

    private void btnReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproducirActionPerformed
        sonido.play();
    }//GEN-LAST:event_btnReproducirActionPerformed

    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
        sonido.stop();
    }//GEN-LAST:event_btnDetenerActionPerformed

    private void PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PagoActionPerformed

    private void DRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DRTActionPerformed

    }//GEN-LAST:event_DRTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiendaGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiendaGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiendaGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiendaGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiendaGV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    public static javax.swing.JComboBox<String> DRT;
    private javax.swing.JButton Pago;
    private javax.swing.JComboBox<String> SelectMusic;
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnReproducir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

    private void buscar() {
        String pl = "";
        if (txtBusqueda.getText().equals("")) {
            pl = DRT.getSelectedItem().toString();
        } else {
            pl = txtBusqueda.getText().trim();
        }

        Music1 v = new Music1();
        String dd = DRT.getSelectedItem().toString();
        oMusica = v.buscar(pl);

        if (oMusica == null) {
            l.setText("El dato ingresado no existe");
            l.setVisible(true);

        } else {
            l.setVisible(false);
            txtArea.setText(oMusica.toString());
            btnReproducir.setVisible(true);
            btnDetener.setVisible(true);
        }
    }

}
